export JAVA_HOME="$(/usr/libexec/java_home -v 11)"
export M2_HOME="/usr/local/Cellar/maven/3.6.0/libexec"
export LDFLAGS="-L/usr/local/opt/libffi/lib"
export PKG_CONFIG="/usr/local/opt/libffi/lib/pkgconfig"
export PUBLIC_IP="$(ipconfig getifaddr en0)"
export PUBLISH_IP="$(ipconfig getifaddr en0)"
export EXTERNAL_IP="$(ipconfig getifaddr en0)"
